language: minimal

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc

install:
  - sudo apt-get install -y npm
  - sudo npm install -g markdown-link-check
  - sudo apt-get install -y python-pip
  - sudo pip install codespell

script:
  - ./build.sh
  - markdown-link-check ./README.md
  - codespell -q4 *.md

deploy:
  provider: pages
  local_dir: static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
