language: minimal

before_install:
  - sudo apt-get update -qq
  - wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb && sudo dpkg -i pandoc-2.7.2-1-amd64.deb

install:
  - sudo apt-get install -y npm nodejs
  - sudo npm install -g markdown-link-check
  - sudo apt-get install -y python-pip
  - sudo pip install codespell

script:
  - ./build.sh
  - markdown-link-check ./README.md
  - codespell -q4 *.md

deploy:
  provider: pages
  local_dir: static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
